import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocalizations extends ChangeNotifier {
  static final AppLocalizations _instance = AppLocalizations._internal();
  factory AppLocalizations() => _instance;
  AppLocalizations._internal();

  static AppLocalizations get instance => _instance;

  String _lang = 'fr';
  String get currentLang => _lang;
  bool get isRtl => _lang == 'ar';

  Future<void> loadSavedLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _lang = prefs.getString('app_language') ?? 'fr';
    notifyListeners();
  }

  Future<void> setLanguage(String lang) async {
    _lang = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', lang);
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_lang]?[key] ??
        _translations['fr']?[key] ??
        key;
  }

  static String t(String key) => _instance.translate(key);

  static final Map<String, Map<String, String>> _translations = {
    'fr': {
      'app_name': 'DZcheptel',
      'login': 'Connexion',
      'login_subtitle': 'Accédez au registre de gestion de votre cheptel.',
      'username_label': 'Identifiant ou Email',
      'username_hint': 'votre.nom@domaine.dz',
      'password_label': 'Mot de passe',
      'password_hint': '••••••••••',
      'remember_me': 'Rester connecté',
      'forgot_password': 'Mot de passe oublié ?',
      'accept_conditions': "J'accepte les ",
      'conditions_link': "conditions d'utilisation",
      'connect_button': 'Se connecter',
      'create_account': 'Créer un compte',
      'already_account': 'Déjà un compte ? ',
      'sign_in': 'Se connecter',
      'field_required': 'Champ requis',
      'accept_conditions_error': "Veuillez accepter les conditions d'utilisation",
      'login_error': 'Identifiant ou mot de passe incorrect',
      'copyright': '© 2024 DZCHEPTEL INDUSTRIAL SYSTEMS • ALGÉRIE ÉLEVAGE',
      'forgot_title': 'Mot de passe oublié ?',
      'forgot_subtitle': "Entrez votre identifiant OU votre adresse email pour retrouver votre compte.",
      'identifier_label': 'Identifiant ou Email',
      'identifier_hint': 'Ex: fermier1 ou email@exemple.com',
      'identifier_info': "Vous pouvez utiliser votre nom d'utilisateur OU votre adresse email.",
      'account_found': 'Compte trouvé !',
      'new_password': 'Nouveau mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'search_btn': 'Rechercher',
      'reset_btn': 'Réinitialiser',
      'password_reset_ok': 'Mot de passe réinitialisé avec succès !',
      'password_reset_msg': 'Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
      'cancel_btn': 'Annuler',
      'accept_btn': 'Accepter',
      'close_btn': 'Fermer',
      'success_title': 'Succès',
      'register_title': 'Créer un compte',
      'register_subtitle': 'Remplissez le formulaire ci-dessous',
      'full_name': 'Nom complet',
      'full_name_hint': 'Ex: Ahmed Benali',
      'username_field': 'Identifiant',
      'username_reg_hint': 'Ex: ahmed.benali',
      'email_field': 'Email',
      'email_hint': 'Ex: ahmed@gmail.com',
      'phone_field': 'Téléphone',
      'phone_hint': 'Ex: 0555123456',
      'password_field': 'Mot de passe',
      'password_reg_hint': 'Minimum 6 caractères',
      'confirm_pass_field': 'Confirmer mot de passe',
      'confirm_pass_hint': 'Répétez votre mot de passe',
      'account_type': 'Type de compte',
      'farmer_role_name': 'Éleveur',
      'farmer_desc': 'Gérer ma ferme et mes animaux',
      'vet_role_name': 'Vétérinaire',
      'vet_desc': 'Gérer les dossiers médicaux',
      'controller_role_name': 'Contrôleur',
      'controller_desc': 'Contrôler et vérifier les effectifs',
      'create_btn': 'CRÉER MON COMPTE',
      'creating': 'Création en cours...',
      'account_created': 'Compte créé avec succès !',
      'scan_rfid': 'Scanner RFID',
      'identification_active': 'Identification active',
      'scan_description': "Positionnez votre terminal près de la puce auriculaire de l'animal.",
      'scan_chip': 'Scanner une puce',
      'scan_camera': 'Scanner via Caméra',
      'manual_input': 'Saisie manuelle',
      'my_animals': 'Mes Animaux',
      'animals_count': 'animaux',
      'profile_tab': 'Profil',
      'dashboard_tab': 'Tableau de bord',
      'species_label': 'ESPÈCE',
      'gender_label': 'SEXE',
      'farm_label': 'FERME',
      'location_label': 'LOCALISATION',
      'status_label': 'STATUT',
      'breed_label': 'RACE',
      'edit_btn': 'Éditer',
      'new_care_btn': 'Nouveau Soin',
      'delete_btn': 'Supprimer',
      'add_animal': 'Ajouter un animal',
      'scan_animal': 'Scannez un animal',
      'total_animals': 'Total Animaux',
      'active_animals': 'Actifs',
      'ovine_animals': 'Ovins',
      'bovine_animals': 'Bovins',
      'quick_actions': 'Actions Rapides',
      'add_btn': 'Ajouter',
      'scan_btn': 'Scanner',
      'journal_btn': 'Journal',
      'sync_btn': 'Sync',
      'alerts_btn': 'Alertes',
      'stats_btn': 'Stats',
      'no_activity': 'Aucune activité',
      'my_farm': 'Ma Ferme',
      'registered_animals': 'Animaux enregistrés',
      'activity_log': "Journal d'activité",
      'notifications_title': 'Notifications',
      'security_title': 'Sécurité',
      'logout_btn': 'Se déconnecter',
      'online_status': 'En ligne',
      'offline_status': 'Hors ligne',
      'offline_banner': 'Mode hors ligne - Les données seront synchronisées',
      'vet_title': 'Vétérinaire',
      'health_sheet': 'Fiche Technique Vétérinaire',
      'select_farm': 'Sélectionner une ferme',
      'medical_history': 'Historique Médical',
      'no_records': 'Aucun dossier médical',
      'add_record': 'Ajouter un Dossier Médical',
      'record_type': 'Type de dossier',
      'vaccination_type': 'Vaccination',
      'disease_type': 'Maladie',
      'treatment_type': 'Traitement',
      'checkup_type': 'Checkup',
      'surgery_type': 'Chirurgie',
      'lab_test_type': 'Analyse Labo',
      'injury_type': 'Blessure',
      'diagnosis_label': 'Diagnostic',
      'treatment_label': 'Traitement prescrit',
      'add_record_btn': 'AJOUTER LE DOSSIER',
      'scan_first': "Scannez d'abord un animal",
      'record_added': 'Dossier médical ajouté avec succès',
      'audit_session': "SESSION D'AUDIT ACTIVE",
      'verify_effectif': "Vérification de l'Effectif",
      'uhf_range': 'SCAN VIA CAMÉRA',
      'uhf_meters': 'Portée : 5-6 mètres',
      'farm_to_control': 'Ferme à contrôler',
      'scanned_tags': 'Tags scannés',
      'no_tags': 'Aucun tag. Cliquez sur Scanner UHF pour commencer.',
      'verify_btn': 'VÉRIFIER',
      'check_btn': 'CHECK',
      'scan_uhf': 'Scanner UHF',
      'animals_detected': 'Animaux Détectés en temps réel',
      'effectif_ok': 'Effectif conforme',
      'gap_detected': 'Écart détecté',
      'missing_tags': 'Tags manquants',
      'unknown_tags': 'Tags inconnus',
      'inventory_confirmed': 'Inventaire confirmé et synchronisé',
      'constat_title': 'Déclaration de Constat',
      'constat_subtitle': 'Déclarez tout écart ou anomalie.',
      'farm_concerned': 'Ferme concernée',
      'constat_description': 'Description du constat',
      'declare_constat': 'DÉCLARER LE CONSTAT',
      'constat_declared': 'Constat déclaré avec succès',
      'constat_saved_offline': 'Constat sauvegardé (sera synchronisé)',
      'conditions_title': "Conditions d'utilisation",
      'conditions_text': "DZcheptel - Plateforme de gestion et traçabilité du cheptel\n\n"
          "1. Fournir des informations exactes et véridiques.\n\n"
          "2. Ne pas utiliser les données d'autrui sans autorisation.\n\n"
          "3. Toutes vos actions sont tracées et journalisées.\n\n"
          "4. Respecter la confidentialité des données.\n\n"
          "5. Les déclarations effectuées ont valeur légale.\n\n"
          "© 2026 HB Technologies - DZcheptel Industrial Systems",
      'confirm_delete': 'Supprimer cet animal ?',
      'delete_warning': 'Cette action est irréversible.',
      'animal_deleted': 'Animal supprimé',
      'synced_msg': 'action(s) synchronisée(s)',
      'nfc_unavailable': 'NFC non disponible',
      'nfc_use_manual': 'Utilisez la saisie manuelle',
      'erase_btn': 'Effacer',
      'back_to_scan': 'Retour au scan',
      'language': 'Langue',
    },
    'en': {
      'app_name': 'DZcheptel',
      'login': 'Login',
      'login_subtitle': 'Access your livestock management registry.',
      'username_label': 'Username or Email',
      'username_hint': 'your.name@domain.dz',
      'password_label': 'Password',
      'password_hint': '••••••••••',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot password?',
      'accept_conditions': 'I accept the ',
      'conditions_link': 'terms and conditions',
      'connect_button': 'Sign in',
      'create_account': 'Create an account',
      'already_account': 'Already have an account? ',
      'sign_in': 'Sign in',
      'field_required': 'Required field',
      'accept_conditions_error': 'Please accept the terms and conditions',
      'login_error': 'Incorrect username or password',
      'copyright': '© 2024 DZCHEPTEL INDUSTRIAL SYSTEMS • ALGERIA LIVESTOCK',
      'forgot_title': 'Forgot password?',
      'forgot_subtitle': 'Enter your username OR email to find your account.',
      'identifier_label': 'Username or Email',
      'identifier_hint': 'Ex: farmer1 or email@example.com',
      'identifier_info': 'You can use your username OR your email address.',
      'account_found': 'Account found!',
      'new_password': 'New password',
      'confirm_password': 'Confirm password',
      'search_btn': 'Search',
      'reset_btn': 'Reset',
      'password_reset_ok': 'Password reset successfully!',
      'password_reset_msg': 'You can now sign in with your new password.',
      'cancel_btn': 'Cancel',
      'accept_btn': 'Accept',
      'close_btn': 'Close',
      'success_title': 'Success',
      'register_title': 'Create account',
      'register_subtitle': 'Fill in the form below',
      'full_name': 'Full name',
      'full_name_hint': 'Ex: Ahmed Benali',
      'username_field': 'Username',
      'username_reg_hint': 'Ex: ahmed.benali',
      'email_field': 'Email',
      'email_hint': 'Ex: ahmed@gmail.com',
      'phone_field': 'Phone',
      'phone_hint': 'Ex: 0555123456',
      'password_field': 'Password',
      'password_reg_hint': 'Minimum 6 characters',
      'confirm_pass_field': 'Confirm password',
      'confirm_pass_hint': 'Repeat your password',
      'account_type': 'Account type',
      'farmer_role_name': 'Farmer',
      'farmer_desc': 'Manage my farm and animals',
      'vet_role_name': 'Veterinarian',
      'vet_desc': 'Manage medical records',
      'controller_role_name': 'Controller',
      'controller_desc': 'Control and verify livestock',
      'create_btn': 'CREATE MY ACCOUNT',
      'creating': 'Creating...',
      'account_created': 'Account created successfully!',
      'scan_rfid': 'Scan RFID',
      'identification_active': 'Active identification',
      'scan_description': 'Place your terminal near the ear tag of the animal.',
      'scan_chip': 'Scan a tag',
      'scan_camera': 'Scan via Camera',
      'manual_input': 'Manual input',
      'my_animals': 'My Animals',
      'animals_count': 'animals',
      'profile_tab': 'Profile',
      'dashboard_tab': 'Dashboard',
      'species_label': 'SPECIES',
      'gender_label': 'GENDER',
      'farm_label': 'FARM',
      'location_label': 'LOCATION',
      'status_label': 'STATUS',
      'breed_label': 'BREED',
      'edit_btn': 'Edit',
      'new_care_btn': 'New Care',
      'delete_btn': 'Delete',
      'add_animal': 'Add animal',
      'scan_animal': 'Scan an animal',
      'total_animals': 'Total Animals',
      'active_animals': 'Active',
      'ovine_animals': 'Ovine',
      'bovine_animals': 'Bovine',
      'quick_actions': 'Quick Actions',
      'add_btn': 'Add',
      'scan_btn': 'Scan',
      'journal_btn': 'Journal',
      'sync_btn': 'Sync',
      'alerts_btn': 'Alerts',
      'stats_btn': 'Stats',
      'no_activity': 'No activity',
      'my_farm': 'My Farm',
      'registered_animals': 'Registered animals',
      'activity_log': 'Activity log',
      'notifications_title': 'Notifications',
      'security_title': 'Security',
      'logout_btn': 'Sign out',
      'online_status': 'Online',
      'offline_status': 'Offline',
      'offline_banner': 'Offline mode - Data will be synced',
      'vet_title': 'Veterinarian',
      'health_sheet': 'Veterinary Technical Sheet',
      'select_farm': 'Select a farm',
      'medical_history': 'Medical History',
      'no_records': 'No medical records',
      'add_record': 'Add Medical Record',
      'record_type': 'Record type',
      'vaccination_type': 'Vaccination',
      'disease_type': 'Disease',
      'treatment_type': 'Treatment',
      'checkup_type': 'Checkup',
      'surgery_type': 'Surgery',
      'lab_test_type': 'Lab Test',
      'injury_type': 'Injury',
      'diagnosis_label': 'Diagnosis',
      'treatment_label': 'Prescribed treatment',
      'add_record_btn': 'ADD RECORD',
      'scan_first': 'Scan an animal first',
      'record_added': 'Medical record added successfully',
      'audit_session': 'AUDIT SESSION ACTIVE',
      'verify_effectif': 'Verify Livestock Count',
      'uhf_range': 'SCAN VIA CAMERA',
      'uhf_meters': 'Range: 5-6 meters',
      'farm_to_control': 'Farm to control',
      'scanned_tags': 'Scanned tags',
      'no_tags': 'No tags. Click Scan UHF to start.',
      'verify_btn': 'VERIFY',
      'check_btn': 'CHECK',
      'scan_uhf': 'Scan UHF',
      'animals_detected': 'Animals Detected in real time',
      'effectif_ok': 'Count matches',
      'gap_detected': 'Gap detected',
      'missing_tags': 'Missing tags',
      'unknown_tags': 'Unknown tags',
      'inventory_confirmed': 'Inventory confirmed and synced',
      'constat_title': 'Report Declaration',
      'constat_subtitle': 'Report any gap or anomaly.',
      'farm_concerned': 'Farm concerned',
      'constat_description': 'Report description',
      'declare_constat': 'DECLARE REPORT',
      'constat_declared': 'Report declared successfully',
      'constat_saved_offline': 'Report saved (will be synced)',
      'conditions_title': 'Terms and Conditions',
      'conditions_text': "DZcheptel - Livestock management platform\n\n"
          "1. Provide accurate and truthful information.\n\n"
          "2. Do not use others data without permission.\n\n"
          "3. All actions are tracked and logged.\n\n"
          "4. Respect data confidentiality.\n\n"
          "5. Declarations have legal value.\n\n"
          "© 2026 HB Technologies - DZcheptel Industrial Systems",
      'confirm_delete': 'Delete this animal?',
      'delete_warning': 'This action is irreversible.',
      'animal_deleted': 'Animal deleted',
      'synced_msg': 'action(s) synced',
      'nfc_unavailable': 'NFC not available',
      'nfc_use_manual': 'Use manual input',
      'erase_btn': 'Clear',
      'back_to_scan': 'Back to scan',
      'language': 'Language',
    },
    'ar': {
      'app_name': 'DZcheptel',
      'login': 'تسجيل الدخول',
      'login_subtitle': 'الوصول إلى سجل إدارة قطيعك',
      'username_label': 'المعرف أو البريد الإلكتروني',
      'username_hint': 'اسم.المستخدم@domaine.dz',
      'password_label': 'كلمة المرور',
      'password_hint': '••••••••••',
      'remember_me': 'تذكرني',
      'forgot_password': 'نسيت كلمة المرور؟',
      'accept_conditions': 'أقبل ',
      'conditions_link': 'شروط الاستخدام',
      'connect_button': 'تسجيل الدخول',
      'create_account': 'إنشاء حساب',
      'already_account': 'لديك حساب؟ ',
      'sign_in': 'تسجيل الدخول',
      'field_required': 'حقل مطلوب',
      'accept_conditions_error': 'يرجى قبول شروط الاستخدام',
      'login_error': 'اسم المستخدم أو كلمة المرور غير صحيحة',
      'copyright': '© 2024 DZCHEPTEL • الجزائر تربية الماشية',
      'forgot_title': 'نسيت كلمة المرور؟',
      'forgot_subtitle': 'أدخل اسم المستخدم أو البريد الإلكتروني للعثور على حسابك.',
      'identifier_label': 'المعرف أو البريد الإلكتروني',
      'identifier_hint': 'مثال: fermier1 أو email@example.com',
      'identifier_info': 'يمكنك استخدام اسم المستخدم أو عنوان بريدك الإلكتروني.',
      'account_found': 'تم العثور على الحساب!',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_password': 'تأكيد كلمة المرور',
      'search_btn': 'بحث',
      'reset_btn': 'إعادة تعيين',
      'password_reset_ok': 'تم إعادة تعيين كلمة المرور بنجاح!',
      'password_reset_msg': 'يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
      'cancel_btn': 'إلغاء',
      'accept_btn': 'قبول',
      'close_btn': 'إغلاق',
      'success_title': 'نجاح',
      'register_title': 'إنشاء حساب',
      'register_subtitle': 'املأ النموذج أدناه',
      'full_name': 'الاسم الكامل',
      'full_name_hint': 'مثال: أحمد بن علي',
      'username_field': 'المعرف',
      'username_reg_hint': 'مثال: ahmed.benali',
      'email_field': 'البريد الإلكتروني',
      'email_hint': 'مثال: ahmed@gmail.com',
      'phone_field': 'الهاتف',
      'phone_hint': 'مثال: 0555123456',
      'password_field': 'كلمة المرور',
      'password_reg_hint': '6 أحرف على الأقل',
      'confirm_pass_field': 'تأكيد كلمة المرور',
      'confirm_pass_hint': 'أعد إدخال كلمة المرور',
      'account_type': 'نوع الحساب',
      'farmer_role_name': 'مربي',
      'farmer_desc': 'إدارة مزرعتي وحيواناتي',
      'vet_role_name': 'طبيب بيطري',
      'vet_desc': 'إدارة الملفات الطبية',
      'controller_role_name': 'مراقب',
      'controller_desc': 'مراقبة والتحقق من الأعداد',
      'create_btn': 'إنشاء حسابي',
      'creating': 'جارٍ الإنشاء...',
      'account_created': 'تم إنشاء الحساب بنجاح!',
      'scan_rfid': 'مسح RFID',
      'identification_active': 'التعريف نشط',
      'scan_description': 'ضع جهازك بالقرب من شريحة الأذن.',
      'scan_chip': 'مسح الشريحة',
      'scan_camera': 'المسح عبر الكاميرا',
      'manual_input': 'إدخال يدوي',
      'my_animals': 'حيواناتي',
      'animals_count': 'حيوان',
      'profile_tab': 'الملف الشخصي',
      'dashboard_tab': 'لوحة القيادة',
      'species_label': 'النوع',
      'gender_label': 'الجنس',
      'farm_label': 'المزرعة',
      'location_label': 'الموقع',
      'status_label': 'الحالة',
      'breed_label': 'السلالة',
      'edit_btn': 'تعديل',
      'new_care_btn': 'رعاية جديدة',
      'delete_btn': 'حذف',
      'add_animal': 'إضافة حيوان',
      'scan_animal': 'مسح حيوان',
      'total_animals': 'إجمالي الحيوانات',
      'active_animals': 'نشط',
      'ovine_animals': 'أغنام',
      'bovine_animals': 'أبقار',
      'quick_actions': 'إجراءات سريعة',
      'add_btn': 'إضافة',
      'scan_btn': 'مسح',
      'journal_btn': 'السجل',
      'sync_btn': 'مزامنة',
      'alerts_btn': 'تنبيهات',
      'stats_btn': 'إحصائيات',
      'no_activity': 'لا يوجد نشاط',
      'my_farm': 'مزرعتي',
      'registered_animals': 'الحيوانات المسجلة',
      'activity_log': 'سجل النشاط',
      'notifications_title': 'الإشعارات',
      'security_title': 'الأمان',
      'logout_btn': 'تسجيل الخروج',
      'online_status': 'متصل',
      'offline_status': 'غير متصل',
      'offline_banner': 'وضع غير متصل - سيتم مزامنة البيانات',
      'vet_title': 'طبيب بيطري',
      'health_sheet': 'البطاقة التقنية البيطرية',
      'select_farm': 'اختر مزرعة',
      'medical_history': 'السجل الطبي',
      'no_records': 'لا توجد سجلات طبية',
      'add_record': 'إضافة سجل طبي',
      'record_type': 'نوع السجل',
      'vaccination_type': 'تطعيم',
      'disease_type': 'مرض',
      'treatment_type': 'علاج',
      'checkup_type': 'فحص',
      'surgery_type': 'جراحة',
      'lab_test_type': 'تحليل مخبري',
      'injury_type': 'إصابة',
      'diagnosis_label': 'التشخيص',
      'treatment_label': 'العلاج الموصوف',
      'add_record_btn': 'إضافة السجل',
      'scan_first': 'امسح حيواناً أولاً',
      'record_added': 'تمت إضافة السجل الطبي بنجاح',
      'audit_session': 'جلسة تدقيق نشطة',
      'verify_effectif': 'التحقق من العدد',
      'uhf_range': 'مسح عبر الكاميرا',
      'uhf_meters': 'المدى: 5-6 أمتار',
      'farm_to_control': 'المزرعة للمراقبة',
      'scanned_tags': 'العلامات الممسوحة',
      'no_tags': 'لا توجد علامات. انقر على مسح UHF للبدء.',
      'verify_btn': 'تحقق',
      'check_btn': 'تأكيد',
      'scan_uhf': 'مسح UHF',
      'animals_detected': 'الحيوانات المكتشفة في الوقت الفعلي',
      'effectif_ok': 'العدد متطابق',
      'gap_detected': 'تم اكتشاف فرق',
      'missing_tags': 'العلامات المفقودة',
      'unknown_tags': 'علامات غير معروفة',
      'inventory_confirmed': 'تم تأكيد الجرد ومزامنته',
      'constat_title': 'إعلان تقرير',
      'constat_subtitle': 'أبلغ عن أي فرق أو خلل.',
      'farm_concerned': 'المزرعة المعنية',
      'constat_description': 'وصف التقرير',
      'declare_constat': 'إعلان التقرير',
      'constat_declared': 'تم إعلان التقرير بنجاح',
      'constat_saved_offline': 'تم حفظ التقرير (سيتم المزامنة)',
      'conditions_title': 'شروط الاستخدام',
      'conditions_text': "DZcheptel - منصة إدارة وتتبع القطيع\n\n"
          "1. تقديم معلومات دقيقة وصادقة.\n\n"
          "2. عدم استخدام بيانات الآخرين بدون إذن.\n\n"
          "3. يتم تتبع وتسجيل جميع الإجراءات.\n\n"
          "4. احترام سرية البيانات.\n\n"
          "5. الإعلانات لها قيمة قانونية.\n\n"
          "© 2026 HB Technologies - DZcheptel Industrial Systems",
      'confirm_delete': 'حذف هذا الحيوان؟',
      'delete_warning': 'هذا الإجراء لا رجعة فيه.',
      'animal_deleted': 'تم حذف الحيوان',
      'synced_msg': 'إجراء(ات) تمت مزامنتها',
      'nfc_unavailable': 'NFC غير متوفر',
      'nfc_use_manual': 'استخدم الإدخال اليدوي',
      'erase_btn': 'مسح',
      'back_to_scan': 'العودة للمسح',
      'language': 'اللغة',
    },
  };
}